### ISSUE TITLE
Question about Example 

### ISSUE THREAD

**Issue by acceleratelch** [naver/nllb-pruning#1]
Hi, and thank you for this amazing work!
I wonder if there is an demo file to prune a light nllb model.
Also, if I want to prune a light model like nllb-200-1.3B, how should I revise the code. Can you give me some advice?
Looking forward to your reply.
Thanks!!!

**Comment by alex-berard** [comment]
Hi, the technique implemented in this repo is for pruning *experts* in a Mixture-of-Expert Transformer. However, NLLB 1.3B (as well as 600M and 3.3B) are not Mixtures of Experts but plain old dense Transformers, so there are no experts to prune.
You'd have to use a different pruning approach.

**Comment by acceleratelch** [comment]
Glad to see your reply.
So I should find other techs to prune light nllb models as they are just plain Transformer model.
Also Thanks for your amazing work and reply!
